# 用于 Intel GPU 的 Compose 文件

services:

  comfyui:
    init: true
    container_name: comfyui-xpu-cn
    build:
      context: .
      dockerfile: Dockerfile
    image: "yanwk/comfyui-boot:xpu-cn"
    ports:
      - "8188:8188"
    volumes:
      - "./storage:/root"
      - "./storage-models/models:/root/ComfyUI/models"
      - "./storage-models/hf-hub:/root/.cache/huggingface/hub"
      - "./storage-models/torch-hub:/root/.cache/torch/hub"
      - "./storage-user/input:/root/ComfyUI/input"
      - "./storage-user/output:/root/ComfyUI/output"
      - "./storage-user/workflows:/root/ComfyUI/user/default/workflows"
    environment:
      - CLI_ARGS=
    devices:
      - /dev/dri
    ipc: host
    security_opt:
      - label:disable
