name: Publish "dev" to Docker Hub

on: 
  workflow_dispatch: # Can be manually triggered

jobs:

  build-publish-dev:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: 'true'
          remove-android: 'true'
      - 
        name: Git checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      -
        name: Build and push 'dev'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-dev
          tags: yanwk/comfyui-boot:dev
          push: true

