name: Publish 'nightly' to Docker Hub

on: 
  workflow_dispatch: # Can be manually triggered
  schedule: # Runs on every Friday, at 00:00 UTC
    - cron: '0 0 * * 5'
  push: 
    branches: [ main ]
    paths-ignore:
      - '**'
      - '!nightly/Dockerfile'
      - '!.github/workflows/build-nightly.yml'

jobs:

  build-test-publish-nightly:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Move Docker data-root to /mnt
        run: |
          sudo systemctl stop docker

          sudo mkdir -p /mnt/docker
          sudo mkdir -p /etc/docker

          cat /etc/docker/daemon.json || true

          sudo tee /etc/docker/daemon.json > /dev/null <<'EOF'
          {
            "data-root": "/mnt/docker"
          }
          EOF

          sudo systemctl restart docker
          docker info | grep "Docker Root Dir"

      -
        name: Get current commit hash
        id: commit
        uses: prompt/actions-commit-hash@v3
      -
        name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      -
        name: Git checkout
        uses: actions/checkout@v6
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build 'nightly'
        uses: docker/build-push-action@v6
        with:
          context: ./nightly
          file: ./nightly/Dockerfile
          build-args: |
            USING_GITHUB_ACTIONS=true
          tags: |
            yanwk/comfyui-boot:nightly
            yanwk/comfyui-boot:nightly-${{ steps.date.outputs.date }}
          load: true
      - 
        name: Show 'nightly' environment variables
        run: |
          docker run --rm \
            --name show-env \
            docker.io/yanwk/comfyui-boot:nightly \
            env
      - 
        name: Test 'nightly'
        run: |
          docker run --rm \
            --name comfyui-quick-test \
            -e CLI_ARGS="--quick-test-for-ci --cpu" \
            yanwk/comfyui-boot:nightly-${{ steps.date.outputs.date }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      -
        name: Push 'nightly'
        uses: docker/build-push-action@v6
        with:
          context: ./nightly
          file: ./nightly/Dockerfile
          build-args: |
            USING_GITHUB_ACTIONS=true
          tags:  |
            yanwk/comfyui-boot:nightly
            yanwk/comfyui-boot:nightly-${{ steps.date.outputs.date }}-${{ steps.commit.outputs.short }}
          push: true
