name: Publish 'rocm7' to Docker Hub

on: 
  workflow_dispatch: # Can be manually triggered
  # schedule: # Runs on every Monday, 07:00 UTC
  #   - cron: '0 7 * * 1'
  push: 
    branches: [ main ]
    paths-ignore:
      - '**'
      - '!rocm7/Dockerfile'
      - '!rocm7/builder-scripts/**'
      - '!rocm7/runner-scripts/**'
      - '!.github/workflows/build-rocm7.yml'

jobs:

  build-publish-rocm7:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: 'true'
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          swap-size-mb: 512
      -
        name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      -
        name: Git checkout
        uses: actions/checkout@v6

      - name: Move Docker data-root to a larger partition (workdir)
        shell: bash
        run: |
          set -euxo pipefail
          NEW_ROOT="$(pwd)/docker-cache"
          docker info --format '{{.DockerRootDir}}'
          docker system df
          sudo systemctl stop docker

          # create new data dir and copy current data (rsync preserves metadata)
          sudo mkdir -p "${NEW_ROOT}"
          sudo rsync -aHAXx /var/lib/docker/ "${NEW_ROOT}"/ || true

          # configure Docker to use the new root
          echo '{"data-root":"'"${NEW_ROOT}"'"}' | sudo tee /etc/docker/daemon.json

          # start Docker back up
          sudo systemctl start docker

          # verify
          docker info --format '{{.DockerRootDir}}'
          df -h "${NEW_ROOT}"

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      -
        name: Build and Push 'rocm7'
        uses: docker/build-push-action@v6
        with:
          context: ./rocm7
          file: ./rocm7/Dockerfile
          build-args: |
            USING_GITHUB_ACTIONS=true
          tags: |
            yanwk/comfyui-boot:rocm7
            yanwk/comfyui-boot:rocm7-${{ steps.date.outputs.date }}
          push: true
