name: Publish 'rocm7' to Docker Hub

on: 
  workflow_dispatch: # Can be manually triggered
  schedule: # Runs on every Monday & Friday, 07:00 UTC
    - cron: '0 7 * * 1,5'
  push: 
    branches: [ main ]
    paths-ignore:
      - '**'
      - '!rocm7/Dockerfile'
      - '!rocm7/builder-scripts/**'
      - '!rocm7/runner-scripts/**'
      - '!.github/workflows/build-rocm7.yml'

jobs:

  build-test-publish-rocm7:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: 'true'
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          swap-size-mb: 512
      # Ugly workaround, checkout first then move docker data-root to the same directory
      # (e.g. /home/runner/work/ComfyUI-Docker/ComfyUI-Docker)
      # which has plenty of space after last step.
      -
        name: Git checkout
        uses: actions/checkout@v6
      -
        name: Move Docker data-root to WORKDIR
        run: |
          WORKDIR=$(pwd)
          echo "PWD=${WORKDIR}"

          sudo systemctl stop docker

          sudo mkdir -p ${WORKDIR}/docker-data
          sudo mkdir -p /etc/docker

          cat /etc/docker/daemon.json || true

          sudo tee /etc/docker/daemon.json > /dev/null <<EOF
          {
            "data-root": "${WORKDIR}/docker-data"
          }
          EOF

          sudo systemctl restart docker
          docker info | grep "Docker Root Dir"

          df -h
      -
        name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build 'rocm7'
        uses: docker/build-push-action@v6
        with:
          context: ./rocm7
          file: ./rocm7/Dockerfile
          build-args: |
            USING_GITHUB_ACTIONS=true
          tags: |
            yanwk/comfyui-boot:rocm7
            yanwk/comfyui-boot:rocm7-${{ steps.date.outputs.date }}
          load: true
      - 
        name: Show 'rocm7' environment variables
        run: |
          docker run --rm \
            --name show-env \
            docker.io/yanwk/comfyui-boot:rocm7 \
            env
      - 
        name: Test 'rocm7'
        run: |
          docker run --rm \
            --name comfyui-quick-test \
            -e CLI_ARGS="--quick-test-for-ci --cpu" \
            yanwk/comfyui-boot:rocm7-${{ steps.date.outputs.date }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      -
        name: Push 'rocm7'
        uses: docker/build-push-action@v6
        with:
          context: ./rocm7
          file: ./rocm7/Dockerfile
          build-args: |
            USING_GITHUB_ACTIONS=true
          tags: |
            yanwk/comfyui-boot:rocm7
            yanwk/comfyui-boot:rocm7-${{ steps.date.outputs.date }}
          push: true
