name: Publish 'nightly' to Docker Hub

on: 
  workflow_dispatch: # Can be manually triggered
  schedule: # Runs on every Friday, at 00:00 UTC
    - cron: '0 0 * * 5'
  push: 
    branches: [ main ]
    paths-ignore:
      - '**'
      - '!nightly/Dockerfile'
      - '!.github/workflows/build-nightly.yml'

jobs:

  build-publish-nightly:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Get current commit hash
        id: commit
        uses: prompt/actions-commit-hash@v3
      -
        name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      -
        name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: 'true'
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          swap-size-mb: 512
      -
        name: Git checkout
        uses: actions/checkout@v6
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      -
        name: Build and push 'nightly'
        uses: docker/build-push-action@v6
        with:
          context: ./nightly
          file: ./nightly/Dockerfile
          build-args: |
            USING_GITHUB_ACTIONS=true
          tags:  |
            yanwk/comfyui-boot:nightly
            yanwk/comfyui-boot:nightly-${{ steps.date.outputs.date }}-${{ steps.commit.outputs.short }}
          push: true
