name: Publish "latest" tag to Docker Hub

on: 
  workflow_dispatch: # Can be manually triggered
  schedule: # Runs on every Monday, 07:00 UTC
    - cron: '0 7 * * 1'
  push: 
    branches: [ main ]
    paths-ignore:
      - 'docker-compose*.yml'
      - 'Dockerfile-rocm'
      - 'README*'
      - 'docs/**'
      - 'storage/**'
      - '.github/**'
      - '!.github/workflows/build-regular.yml'


jobs:

  build-publish-latest:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: 'true'
          remove-android: 'true'
      - 
        name: Git checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      -
        name: Build and push 'latest'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: yanwk/comfyui-boot:latest
          push: true
