name: Test 'cu128-slim' from Docker Hub

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish 'cu128-slim' to Docker Hub"]
    types:
      - completed

jobs:
  test-image-cu128-slim:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image from Docker Hub
        run: docker pull docker.io/yanwk/comfyui-boot:cu128-slim

      - name: Run container with quick-test
        run: |
          env \
          && docker run --rm \
            --name comfyui-quick-test \
            -e CLI_ARGS="--quick-test-for-ci --cpu" \
            docker.io/yanwk/comfyui-boot:cu128-slim
